crates/evm/src/eth.rs, crates/op-evm/src/lib.rs
Closes #9
swaps the individual blockenv values instead of cloning the entire block env.
=> chore: swap blockenv values instead of cloning 

Cargo.toml, crates/evm/Cargo.toml, crates/evm/src/eth.rs, crates/evm/src/evm.rs, crates/evm/src/lib.rs, crates/evm/src/tx.rs, crates/op-evm/src/lib.rs
ref https://github.com/paradigmxyz/reth/issues/14551
This PR introduces two traits:
- `IntoTxEnv` - core conversion trait performing simple conversion from a `Tx` to `TxEnv` type. `impl IntoTxEnv<Self::Tx>` is now used as input on `Evm::transact` allowing to extend a set of transaction environment types that can be passed 
- `FromRecoveredTx` - a helper trait to provide `IntoTxEnv` implementations for `Recovered<Tx>`
This should allow us to cover all of the usecase as all of `TxEnv`, `Recovered<Tx>`, `Recovered<&Tx>` are now valid inputs for Evm, and users are still free to define `IntoTxEnv` for any external types.
One required hack is that any Evm impl has to define for `IntoTxEnv<Self>` for the `Evm::Tx` which is not perfect but is not that bad generally as we already require similar …
=> feat: `TxEnv` conversion traits

crates/evm/src/evm.rs
This clone is expensive and is not really needed as state is already accessible when calling `transact` and `commit` separately
=> refactor: do not clone state on `transact_commit`

crates/evm/src/block/system_calls/mod.rs
adds helper fns that make it possible to invoke the state hook with a closure so that we're not required to always collect the evmstate and can do that in a closure instead
can be used after #26
=> feat: add state hook closure fns

crates/evm/src/block/system_calls/eip2935.rs, crates/evm/src/block/system_calls/eip4788.rs, crates/evm/src/block/system_calls/eip7002.rs, crates/evm/src/block/system_calls/eip7251.rs, crates/evm/src/eth/mod.rs, crates/evm/src/evm.rs, crates/op-evm/src/lib.rs
There's an edge case when system contract is set to block beneficiary, so we can't simply remove it from the state. The assumption here is that there will not be any state changes to beneficiary due to fee accounting, and we can safely keep it in the state.
=> fix: correctly handle state after system calls

crates/op-evm/src/lib.rs
Assigns the deposit tx type to system call transactions, so that `op-revm` skips transaction fee validation for them. The operator fee now can charge a non-zero fee even if the base fee is zero, and this bypasses the check and the attempted charge for pre-block syscalls.
http://github.com/bluealloy/revm/blob/080c29a2aef640063c7bcb30834ef7e998b8efe2/crates/optimism/src/handler.rs#L89-L90
=> fix(isthmus): Assign deposit tx type to system call txs

crates/evm/src/tx.rs
The trait bound on the `EthereumTxEnvelope` implementations are too strict for `Eip4844`. This particular generic has multiple implementations that could fit.
Make use of https://github.com/alloy-rs/alloy/pull/2272 and relax the bounds to `AsRef<TxEip4844>`.
=> feat(tx): Relax bounds on `TxEip4844` for `EthereumTxEnvelope`

crates/evm/src/block/mod.rs, crates/evm/src/eth/block.rs, crates/op-evm/src/block/mod.rs
Currently, the opstack use-case of `eth_simulate` on reth charges user L1 data cost due to the way tx envelope is derived for serialized transaction.
This is divergent from op-geth logic, where the L1 data cost is not charged.
The simulation fails for users with lower balance, where it should not fail.
Allows for empty envelopes as part of https://github.com/paradigmxyz/reth/issues/15292
Empty envelopes will contain zero L1 data cost.
A `FromTxWithEncoded` trait bound is added to associated transaction type on `BlockExecutor`. This allows to create the tx envelope using `WithEncoded::new(Default::default(), tx)`
=> feat(tx): Add `FromTxWithEncoded` bound to `BlockExecutor` transaction

Cargo.toml
Bumps `op-revm`, including a patch for Isthmus.
=> chore: Bump `op-revm` to `3.0.1`

crates/evm/src/lib.rs, crates/evm/src/precompiles.rs
closes #70
instead of making possible to configure a custom precompiles provider on the factory level, we should instead make it possible to modify the precompiles via the evm on demand.
but we can also solve this with another constructor fn on EvmFactory, however, then we still need to use one specific PrecompileProvider type.
since this turned out to be a bit tricky with GATs, we can introduce our own Precompiles type that supports the usecases we want: hotswapping function pointers for example.
and we can offload all custom functionality directly into the precompile fn pointer instead of doing this: https://github.com/paradigmxyz/reth/pull/15536
=> feat: add SpecPrecompiles

crates/evm/src/eth/mod.rs, crates/evm/src/evm.rs, crates/op-evm/src/lib.rs
towards #70
After #71, which allowed modifying precompiles at runtime, we need to make the functionality accessible to evm consumers.
Adds a `Precompiles` associated type and a `precompiles_mut` method to the `Evm` trait.
=> feat: include Precompiles associated type in Evm trait

crates/evm/src/lib.rs
Re-export revm and op-revm for easier version control.
Re-export them in `crates/evm/src/lib.rs`.
=> chore: re-export revm & op-revm

crates/evm/src/block/state_changes.rs, crates/evm/src/precompiles.rs
fixes errors like:
```
error[E0308]: mismatched types
--> /home/fgimenez/.cargo/git/checkouts/evm-136cfc19c7c10910/198219d/crates/evm/src/block/state_changes.rs:70:9
|
66  |     insert_post_block_withdrawals_balance_increments(
|     ------------------------------------------------ arguments to this function are incorrect
...
70  |         &mut balance_increments,
|         ^^^^^^^^^^^^^^^^^^^^^^^ expected `&mut HashMap<Address, u128, RandomState>`, found `&mut HashMap<_, _>`
|
= note: `std::hash::RandomState` and `RandomState` have similar names, but are actually distinct types
```
=> fix: use HashMap::with_capacity_and_hasher

crates/evm/Cargo.toml, crates/evm/src/tx.rs
Closes #75 
Leverages faster `secp256k1` crate based algorithm if `std` feature flag is on
The `alloy` have a new sender recovery algorithm using `secp256k1` crate. It was found in benchmarks that this crate's algorithm is significantly faster than the existing `k256`, but requires `std` making it usable only on platforms that allow it.
Recover authority list of EIP-7702 transaction using the `alloy_consensus::crypto` module to recover the signer.
=> feat(eip7702): Delegate signer recovery to `alloy-consensus::crypto`

Cargo.toml, crates/evm/src/precompiles.rs
Whilst bumping to `alloy-evm` v0.7.1 I encountered this issue
This only occurs when `alloy-evm` is integrated (in this case Foundry); it is not raised when I clone and compile `alloy-evm` from source
I think this code is equivalent and resolves the compiler error downstream for Foundry
cc @mattsse / @klkvr
=> fix: `r.as_ref()` the trait `AsRef<[_; 0]>` is not implemented for `[u8]`

crates/evm/src/evm.rs
We need to include EVM's `Spec` AT  in reth's precompile cache key for https://github.com/paradigmxyz/reth/issues/16207 this PR adds the missing bounds required
=> feat: extend Evm::Spec bounds with Hash and PartialEq

crates/evm/src/either.rs, crates/evm/src/eth/mod.rs, crates/evm/src/evm.rs, crates/op-evm/src/lib.rs
Encountered a case where I want to access a field on the`inspector` without it needing to be mutable. For code hygiene purposes accessing it non-mutable would be preferred (see: https://github.com/foundry-rs/foundry/pull/10555)
Adds non-mutable getters for `precompiles` and `inspector` mirroring the current `precompiles_mut` and `inspector_mut`
=> feat: add non-mutable getters for `inspector` and `precompiles`

crates/evm/src/tx.rs
While working on the `custom_node` example I intended to implement `FromTxWithEncoded<CustomTransaction> for CustomTxEnv` and the same with `FromRecoveredTx`. The approach I took was to redirect to `FromTxWithEncoded<Inner> for TxEnv`. This is, however, not implemented for `TxEnv`, but only for `OpTransaction<TxEnv>`
Extract `impl FromTxWithEncoded<OpTxEnvelope> for TxEnv` and `FromRecoveredTx` counterpart from `impl FromTxWithEncoded<OpTxEnvelope> for OpTransaction<TxEnv>`
=> feat: Implement `FromTxWithEncoded` and `FromRecoveredTx` from `OpTxEnvelope` for `TxEnv`

crates/evm/Cargo.toml, crates/evm/src/call.rs, crates/evm/src/lib.rs
Adds a new `call-util` feature that provides utilities for eth_call and adjacent RPC endpoints. 
The initial implementation includes the `caller_gas_allowance` function ported from reth, which calculates the maximum gas a caller can afford based on their balance and the transaction's gas price.
- Added new `call-util` feature to Cargo.toml that depends on `overrides` feature (for alloy-rpc-types-eth)
- Created new `call` module with utilities for RPC call endpoints
- Implemented `caller_gas_allowance` function that calculates how much gas a caller can afford
- Added proper error handling with `CallError` enum and dedicated `InsufficientFundsError` struct
=> feat: add call-util feature with caller_gas_allowance

crates/evm/src/tracing.rs
```markdown
A minor documentation fix that corrects a typo in a comment within `crates/evm/src/tracing.rs`.
**Change:**
- `commited` -> `committed`
```
=> docs: Fix typo in tracing.rs comment

crates/evm/src/precompiles.rs
As raised here: https://github.com/alloy-rs/evm/pull/100#discussion_r2163451799 looks to be a regression of https://github.com/alloy-rs/evm/pull/86 during port to revm 26
In Foundry we are getting the following error on the `r.as_ref()` line: https://github.com/alloy-rs/evm/blob/5ed2c8e435aa7e2a14c20b99b669fccd28fc198d/crates/evm/src/precompiles.rs#L239 when using the library in https://github.com/foundry-rs/foundry/tree/zerosnacks/bump-revm-26.0.0:
```
the trait bound `[u8]: AsRef<[_; 0]>` is not satisfied
the following other types implement trait `AsRef<T>`:
`[u8]` implements `AsRef<winnow::stream::bstr::BStr>`
`[u8]` implements `AsRef<winnow::stream::bytes::Bytes>`
```
Fixes type mismatch, turns it into a `&[u8]`
=> fix: `the trait bound `[u8]: AsRef<[_; 0]>` is not satisfied` in `precompiles`

crates/evm/src/precompiles.rs, crates/evm/src/traits.rs
this way precompiles can access the block context such as timestamp number etc.
=> feat: add BlockEnv to EvmInternals

crates/evm/src/block/state_changes.rs
we know how many entries we need
=> perf: allocate capacity for balance changes

crates/evm/src/precompiles.rs
add a way to consume the map and return the underlying list of precompiles
=> chore: add into_dyn_precompiles

crates/evm/src/block/mod.rs, crates/evm/src/eth/block.rs, crates/evm/src/tx.rs, crates/op-evm/src/block/mod.rs
The way we've designed and use most of the APIs is by passing transactions directly to EVM/block executors, thus using `IntoTxEnv` does not make perfect sense as it consumes `self` while we're mostly doing `&self -> TxEnv` conversions now.
This PR introduces `BuildTxEnv` which takes `&self` and is automatically implemented for references. This allows to simplify some of the `TxEnv` implementations and drop `Copy` supertrait from `ExecutableTx`, allowing to pass owned transactions to block executors instead of just references.
The only `IntoTxEnv` implementations are now for `BuildTxEnv` and for `Self`
=> feat: `ToTxEnv`

crates/evm/src/precompiles.rs
Implements `map_pure_precompiles` to filter out non-pure precompiles that may have side effects when caching. Adds helper method `map_precompiles_filtered` for conditional precompile transformations.
Closes paradigmxyz/reth#17870
=> feat: add map_pure_precompiles to respect pure precompiles for caching

crates/evm/src/block/error.rs
Right now arbitrary error messages can only be converted into `BlockExecutionError::Internal` variant which is not perfect as it causes reth engine to treat errors as internal ones vs caused by invalid block.
=> feat: add `BlockValidationError::Other`

crates/op-evm/src/block/mod.rs
I am trying to make customizations to the `OpBlockExecutor`s execution logic, e.g. pre loading receipts, and a bundle into the evm. This is not possible to do without duplicating the code as the fields are not publicly exposed.
Make all fields pub on `OpBlockExecutor`, and `OpBlockExecutorFactory`
=> chore: make OpBlockExecutor fields pub

crates/evm/src/precompiles.rs
helper to iterate over all identifiers
=> chore: add precompileid helper
