alloy-rs/evm

- crates/evm/src/eth.rs
- crates/op-evm/src/lib.rs
> fix: correctly use inspectors

- Cargo.toml
> chore: bump revm

- crates/evm/src/error.rs
> feat: add `EvmError::try_into_invalid_tx_err`

- crates/evm/src/evm.rs
This should always be `'static`
> chore: add 'static bound to HaltReason

- crates/evm/src/eth.rs
- crates/evm/src/evm.rs
- crates/op-evm/src/lib.rs
It is useful to have a way to convert `Evm` back into `EvmEnv` once we're done with it. This requires removing `Input` generic on `EvmFactory` in favor of `Spec` AT. This means we can't define multiple inputs for the same factory type which is imo fine as Evm still takes fixed type as input, and custom inputs can be solved with additional traits (e.g like we've done it with `ConfigureEvmEnv` in reth)
> refactor: embed EvmEnv into abstraction

- Cargo.toml
- deny.toml
> chore: bump alloy-eips

- Cargo.toml
- crates/evm/src/env.rs
- crates/evm/src/eth/mod.rs
- crates/op-evm/src/lib.rs
> chore: use released revm

- Cargo.toml
> chore: use released hardforks

- crates/evm/src/tx.rs
Closes https://github.com/paradigmxyz/reth/issues/15454
Recently added trait bounds to transaction types include `FromTxWithEncoded` as seen in #54.
* Implements `FromTxWithEncoded` for all variants of `TxEnv` that **ignores encoded bytes**
* Implements `FromTxWithEncoded` and `FromRecoveredTx` for `EthereumTxEnvelope`
> feat(tx): Implement `FromTxWithEncoded` and `FromRecoveredTx` for `EthereumTxEnvelope`

- Cargo.toml
- crates/evm/src/eth/eip6110.rs
- crates/op-evm/src/block/mod.rs
> chore: alloy 0.14

- crates/evm/src/env.rs
- crates/evm/src/eth/mod.rs
- crates/evm/src/evm.rs
- crates/op-evm/src/lib.rs
> feat: added method to get chain id

- Cargo.toml
- crates/evm/src/block/state_changes.rs
- crates/evm/src/eth/mod.rs
- crates/evm/src/precompiles.rs
- crates/evm/src/tx.rs
- crates/op-evm/src/lib.rs
Builds on top of #73
Closes #70 
* Patches revm and op-revm to a commit that has `OpPrecompiles::precompiles()` and `OpEvm::with_precompiles`
* Changes in `EvmFactory for OpEvmFactory` to use `PrecompilesMap`
> feat: bump revm

- crates/evm/src/precompiles.rs
this entire match looks very cursed -.-
> chore: use as_ref

- crates/evm/src/block/mod.rs
- crates/evm/src/eth/block.rs
- crates/op-evm/src/block/mod.rs
Adds a new `execute_transaction_with_commit_condition` helper that allows to inspect the transaction outcome and commit it conditionally based on it.
> feat: `BlockExecutor::execute_transaction_with_commit_condition`

- crates/evm/src/tx.rs
> feat: Implement from_recovered_tx for txDeposit nativel

- Cargo.toml
- crates/evm/src/tx.rs
ref [#16310](https://github.com/paradigmxyz/reth/pull/16310)
> chore: preparing for mint nonoptional in reth

- crates/evm/src/precompiles.rs
> chore: derive Copy for `PrecompileInput`

- crates/evm/src/env.rs
these are helpful when applying overrides
> feat: add setter utils to blockenv

- crates/evm/src/precompiles.rs
Implements the `is_pure` method for the `Precompile` trait as described in #125. This allows precompiles to declare whether their output is deterministic based solely on input, enabling potential caching optimizations.
- Added `is_pure` method to the `Precompile` trait with a default implementation returning `false`
- Updated trait implementations to properly delegate `is_pure` calls:
- `DynPrecompile` and `&DynPrecompile` now delegate to their inner precompile
- `Either<A, B>` delegates to the appropriate variant
- Added comprehensive documentation explaining the purpose and usage of `is_pure`
- Added tests to verify the implementation works correctly for all trait implementations
The conservative default of `false` ensures existing precompiles that depend on state continue to work …
> feat: add is_pure method to Precompile trait

- crates/evm/src/eth/mod.rs
- crates/op-evm/src/lib.rs
Superseeds https://github.com/alloy-rs/evm/pull/68
closes https://github.com/alloy-rs/evm/issues/51#event-17248333584
> chore: use revm system_call

- crates/evm/src/traits.rs
Adds a way to emit logs via `EvmInternals`
> feat: `EvmInternals::log`

- crates/evm/src/error.rs
https://github.com/paradigmxyz/reth/pull/17573
> feat: add as_invalid_tx_err in InvalidTxError

- crates/evm/src/tx.rs
> feat: more impls for `Either`

- crates/evm/src/precompiles.rs
Re-applies changes from fusaka-devnet-3
> feat: expose `PrecompileId`
